CREATE TABLE USER (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASS VARCHAR(255),
    CREATED_ON_DATETIME DATE
)

-- CREATE TABLE TEMPERATURE(
-- 	TEMPERATURE_ID 
-- 	
-- )